### ISSUE TITLE
More COLOR!

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/snek#14]
Let's give the game board a little more color. How about a CSS background of a grass pattern (or dirt or whatever looks good). Please change the snake to a color as well. A snake-like color - something that won't clash with the background but isn't black.

**Comment by JaqueLB** [comment]
I will try this one

**Comment by Pamblam** [comment]
Thanks!

**Comment by BrNaka** [comment]
I'm 

> I will try this one

I'm sorry @JaqueLB. I didn't see your message before. I opened a _Pull Request_ for this issue... my mistake. I apologise.
