### ISSUE TITLE
Input Styling

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/snek#17]
Please add some style to the input and the button (where it asks for your name). Right now they have no styles at all.

**Comment by mobeenabdullah** [comment]
Hey Pamblam,

I am new in participating in Hactoberfest. Don't know I followed the process right or wrong but I styled the field.

What I did is:

1) I forked the Repo.
2) I added new CSS in index.css
3) I commit the changes.

See changes here:
https://github.com/mobeenabdullah/snek/blob/master/index.css

**Comment by mobeenabdullah** [comment]
I think now I successfully made the PR. Please approve it.

**Comment by Pamblam** [comment]
All set and approved @mobeenabdullah . Thank you for contributing. Please add your name to the README under contributors since you contributed. That's a second easy PR if you're trying to get the Hacktoberfest swag.

**Comment by mobeenabdullah** [comment]
Sure thing, on it now. Thanks Buddy :)
