### ISSUE TITLE
Option to 'fast forward' snek

### ISSUE THREAD

**Issue by DirtySoc** [Pamblam/snek#42]
In the early parts of the game you have to wait a long time for the snek to travel across the screen. Maybe a FF hotkey or method should be implemented.

**Comment by Pamblam** [comment]
that's a great idea. i had considered something like that myself.

**Comment by Pamblam** [comment]
I sped him up a little bit and made him gain more length for each tomato he eats.. i also added cherries that show up every couple of minutes at random that give him a temporary speed boost.
