### ISSUE TITLE
Default canvas size not listed in canvas sizing options.

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/snek#44]
By default a canvas is 300x150. This is the dimensions of the canvas until they are resized by the user. These dimensions should be added to the dimensions list at the top so it is selected by default. The dimensions list is in a function somewhere near the bottom of `snek.js`.

**Comment by Joel-hanson** [comment]
I have made the pull request for this bug.

**Comment by Pamblam** [comment]
@Joel-hanson I think the PR you submitted was for another issue - the one about the spacebar.

**Comment by Joel-hanson** [comment]
sorry

**Comment by Joel-hanson** [comment]
I have made the pull request for this bug and this is not a mistake :).
