### ISSUE TITLE
Add a timer

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/snek#48]
Add a timer (minutes and seconds) that keeps track of gameplay time and pauses when the user pauses the game and place it someplace above the game board.

**Comment by saravanan10393** [comment]
@Pamblam can i take this.

**Comment by Pamblam** [comment]
Thank you @saravanan10393. Please remember to add your name to the readme.

**Comment by saravanan10393** [comment]
@Pamblam  pull request given. Check out #57 and comment your feedback.
