### ISSUE TITLE
🎃 🍅 Let's make it a tomato like 70% of the time

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/snek#87]
The food was originally a tomato ([see here](https://github.com/Pamblam/snek/blob/e958d9efb9c215bf19e48c2fb1a84bf0fa2422a5/scripts/game.js#L91)), but someone changed it to a jack-o-lantern for Hacktoberfest ([see here](https://github.com/Pamblam/snek/blob/multiplayer/scripts/game.js#L117)).

Let's make it randomly switch between one and the other, let it be a tomato like 70% of the time and a jack-o-lantern like 30%..

Basically, here's what needs to be done. 

 - Create a global variable at the top called `food_char` or something.
 - In the draw function where it checks `if(!food)` we need to have it also [generate a random number between 1 and 10](https://stackoverflow.com/questions/1527803/generating-random-whole-numbers-in-javascript-in-a-specific-range), if the number is 7 or greater, set the `food_char` to the value of the jac-o-lantern character, else set it to the value of the tomato.
 - Change the `ctx.fillText(...)` to use the variable instead of the literal character.

This should be a real simple task for someone.

**Comment by shivakaushal** [comment]
@Pamblam I'll take this

**Comment by Pamblam** [comment]
Thank you!

**Comment by Yoldrim** [comment]
Solved!
