### ISSUE TITLE
Make the image a gif

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/snek#91]
The image of the game in the README should be animated. Take a screencast of the game in play in two-player mode and replace the static image. preferably using the same 400x400 size game board.

**Comment by michaelprflores** [comment]
Hello. Submitted a PR to help with this. https://github.com/Pamblam/snek/pull/93/commits/82ef8af342a0e805e4f6dd3c686830a1691b7600

**Comment by Pamblam** [comment]
Hello, @michaelprflores - Thank you so much for contributing, but you committed it to the master branch, our working branch is the multiplayer branch. In the top left corner of the page use the branches drop down to select the multiplayer branch.

<img src='https://i.imgur.com/DuirMLX.png' />

Then for that branch, run the code in your localhost and you will see the two-player mode that we're currently working on. Please make the image of the game in 2 player mode since that is the focus of the next release.

Thank you.

**Comment by smrsan76** [comment]
Hi @Pamblam 
I've recently submitted a PR.
Please check it 👉 [b9b0f6e](https://github.com/Pamblam/snek/pull/94/commits/b9b0f6e1c2b804ebc310eef772db515bb364b952)

**Comment by Pamblam** [comment]
@smrsan76 looks great! thanks a lot!

**Comment by smrsan76** [comment]
@Pamblam 😉
