### ISSUE TITLE
Move the game-board size drop-down to the main form.

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/snek#92]
Before the game starts there is a drop down that lets you choose the size of the board. Please move that to the main form at the beginning of the game instead.

**Comment by visvxplore** [comment]
I was getting "ReferenceError. snekHeads is not defined" after merge. I tried modifying the unused variable name snekHead to snekHeads, results type errors to snekHeads.brown so on... I can't get the purpose of snekHead or snekHeads, the game doesn't loading any further than showing up the logo.

**Comment by niilz** [comment]
Has this been fixed already? The drop down appears right above the bord in my browser (chrome). If the move is still supposed to happen, please let me know which main form you ment and I would love to move the drop down.

**Comment by visvxplore** [comment]
Hi niilz, by main form @Pamblam meant to move the drop down on the place where you have been entering the user name. So this improvement makes us to submit the user name and the selection of game resolution before starting to play.

**Comment by niilz** [comment]
I seeee. That makes sence. Thank you. Yeah, I would like to get on to that

**Comment by Pamblam** [comment]
Hey, If you have the `snekHead` variabel instead of `snekHeads` you might have pulled from the master branch. Please make sure you are using the `multiplayer` branch. Let me know if you need further clarification on how to do that.

**Comment by niilz** [comment]
To be honest: I am struggeling. It was fine to move the the dropdown onto the main page. I had pulled it outside the form (below the user input field).
But that means it appears below the ranks-table at the game site. If I keep it above, i can't find a short way to work around the .hidden rule on the container.
I was thinking about removing the select element on page load (after username is chosen) and then rebuilding it at the next page, but that seems quite hacky.
I have no time tomorrow to go on with the issue, so if someone wants to take over please don't wait for me. I will get back to it though (even if it is just for my own experience since I am very new to the coding world after all).

**Comment by Pamblam** [comment]
@niilz  - Thank you for trying. I'd be happy to give you a pointer or two but I'll need to see what you've done so far. If you commit and push whatever you have done up to your fork - then you can click on the settings menu on your fork - go down to github pages and have it use the master branch for you github page for that repo. That way I will be able to view your code changes at https://nillz.github.io/snek/

**Comment by niilz** [comment]
thanks for your reply. I have changed my approach a little.
I duplicated the drop down. So it also appears below the user name field. (At the moment this still appears below the rank list in the game view)
Both have a class of "resolution" instead the one having an id.
I then thought I could store the canvas width and height in localStorage to build the canvas from those parameters. Buuut unfortunately this does not work ye.
I have added the code to my fork under the branch add_size_to_main.
If you really have time to look at it I would highly appreciate your thoughts.
THX

**Comment by Pamblam** [comment]
Hey @niilz, I looked at your repo, but before I can really give you any advice on code you'll have to switch over to the `multiplayer` branch. The `master` branch is version 1, we are no longer working on v1 any more. We are working on version 2 now, which is in the `multiplayer` branch. Your `add_size_to_main` branch is a fork of the master branch, which doesn't even have the main form :stuck_out_tongue:.

![master branch](https://i.imgur.com/R9KbTOA.png)

So what we're actually trying to do here is move this dropdown...

![size dropdown](https://i.imgur.com/PA6MmSL.png)

into this form

![main form](https://i.imgur.com/GpyFe7F.png)

But that form actually doesn't exist on the branch you made. So you can go ahead and  delete that branch you just made, and delete the code locally.

Now checkout your multiplayer branch like this...

`git clone --single-branch -b multiplayer https://github.com/niilz/snek.git`

Then, in the `index.html` file, starting on line 22 is a select box: 

`<select name="resolution" id="resolution"></select>`

You wanna take that and move it into the form that starts on line 49. That will probably work as-is. I'm not sure if you need to change any Javascript at all actually.

Then test it out, commit and make a PR :sunglasses:

**Comment by Pamblam** [comment]
Dude it says it in big letters in the readme. I've said twice wo far in this thread alone. **You must use the multiplayer branch.** If you'd like to try again please do.

**Comment by Pamblam** [comment]
Thanks for sticking with it!

**Comment by niilz** [comment]
You are very welcome.
BIG THANKS to you though for mentoring me on this. Learned a lot about PRs. 👍
